/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relFatuDk;

import br.com.iltonti.dal.ModuloConexao3M;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ilton
 */
public class RelFatuDkTela extends javax.swing.JFrame {

    /**
     * Creates new form RelFatuDkTela
     */
    public RelFatuDkTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDtIni = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter txtDataIni= new javax.swing.text.MaskFormatter("##/##/####");  
            txtDtIni = new javax.swing.JFormattedTextField(txtDataIni);  
        }  
        catch (Exception e){  
        }
        btnGeraRel = new javax.swing.JToggleButton();
        txtDtFim = new javax.swing.JTextField();
        try{  
            javax.swing.text.MaskFormatter txtDataIni= new javax.swing.text.MaskFormatter("##/##/####");  
            txtDtFim = new javax.swing.JFormattedTextField(txtDataIni);  
        }  
        catch (Exception e){  
        }
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtDtIni.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDtIni.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnGeraRel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGeraRel.setText("Gerar Relatório");
        btnGeraRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraRelActionPerformed(evt);
            }
        });

        txtDtFim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDtFim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDtFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtFimActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Inicial");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Final");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Relatório de Faturamento");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VR DOCTOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDtIni)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDtFim)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnGeraRel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDtFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addComponent(btnGeraRel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeraRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraRelActionPerformed
        // TODO add your handling code here:
        
        String dtInicialA = txtDtIni.getText();
        System.out.println("A= " + dtInicialA);        
        
        String dtFimB = txtDtFim.getText();
        System.out.println("B= " + dtFimB);        
        /*
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        Date dataInverte = formato.parse(dtInicialA);
        System.out.println("B= " + dataInverte);
        System.out.println("C= " + formato.format(dataInverte));
        String dataRelatorio = formato.format(dataInverte);
        System.out.println(dataRelatorio);
        */                
        Connection conexao = null;
        conexao = ModuloConexao3M.conector();
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        /*
        //HashMap antigo, sem preparar data
        HashMap parametros = new HashMap();
        parametros.put("dtIni", txtDtIni.getText());
        parametros.put("dtFim", txtDtFim.getText());       
        System.out.println(parametros);
        */
        
        //Ajustando a Data Inicial
        SimpleDateFormat dIniForm = new SimpleDateFormat("dd/MM/yyyy");
        dIniForm.setLenient(false);
        Date dataInicial = null;
        try {
            dataInicial = dIniForm.parse(dtInicialA);
        } catch (ParseException ex) {
            Logger.getLogger(RelFatuDkTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        dIniForm = new SimpleDateFormat("yyyy-MM-dd");
        String saidaDtInicial = dIniForm.format(dataInicial);
        System.out.println("Data Inicial Formatada= " + saidaDtInicial);
        
        //Ajustando a Data Final
        SimpleDateFormat dFimForm = new SimpleDateFormat("dd/MM/yyyy");
        dFimForm.setLenient(false);
        Date dataFim = null;
        try {
            dataFim = dFimForm.parse(dtFimB);
        } catch (ParseException ex) {
            Logger.getLogger(RelFatuDkTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        dFimForm = new SimpleDateFormat("yyyy-MM-dd");
        String saidaDtFim = dFimForm.format(dataFim);
        System.out.println("Data Final Formatada= " + saidaDtFim);
        
        //HashMap com data preparada
        HashMap parametros = new HashMap();
        parametros.put("dtIni", saidaDtInicial);
        parametros.put("dtFim", saidaDtFim);       
        System.out.println(parametros);
        
     
        //imrpimindo relatorio com o Jasper
        try {
            System.out.println("Passagem para Rel = " + parametros);
            JasperPrint print = JasperFillManager.fillReport("C:\\Shop9\\Arq3m\\relFaturaVR.jasper", parametros, conexao);
        // exibe o relatorio
            JasperViewer.viewReport(print, false);
        // EXPORTA o relatorio para PDF
            JasperExportManager.exportReportToPdfFile(print, "C:\\Shop9\\Arq3m\\RelatorioFaturaVR.pdf");           
            
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try {
            conexao.close();
            System.out.println("Fechei a conexão com o BD. ");
        } catch (SQLException ex) {
            Logger.getLogger(RelFatuDkTela.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_btnGeraRelActionPerformed

    private void txtDtFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtFimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelFatuDkTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelFatuDkTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelFatuDkTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelFatuDkTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelFatuDkTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnGeraRel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDtFim;
    private javax.swing.JTextField txtDtIni;
    // End of variables declaration//GEN-END:variables
}
